### ISSUE TITLE
Too many files error

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/bazel-watcher#109]
I tried using the tool on my project, and get the following error message many times:

Error: too many open files

**Comment by solomatov** [comment]
It's easy to workaround by invoking ulimit -n 10000 before invoking ibazel.

**Comment by jasonaden** [comment]
Would be great to get a fix so the workaround isn't needed.

**Comment by achew22** [comment]
This would be pretty easy to fix in [main.go](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/main.go#L121) right before calling handle. Looks like it's [pretty easy](https://stackoverflow.com/a/17818022). This would be a great first contribution

**Comment by coltonmorris** [comment]
My node_modules is giant, and the ulimit workaround just isn't enough. Would an exclusion option be a good way to handle this?

**Comment by achew22** [comment]
@coltonmorris Interesting. We now set the ulimit automatically [at startup](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/main.go#L153) to be the biggest possible. Is it possible to check the version of iBazel you're running?

**Comment by coltonmorris** [comment]
0.5.0.
I've also tried manually setting it.

**Comment by dougkoch** [comment]
@coltonmorris In your case, setting `ulimit -n` to the hard limit (which is what `ibazel` does automatically) may not have been sufficient to cover the number of files in your `node_modules`. For example, on my Ubuntu system, the default soft and hard limits are 1024 and 4096, respectively, so a non-root user can't set it any higher than 4096. Did you try changing the hard limit? On Linux, this just requires editing `/etc/security/limits.conf` as root; if you're using a Mac you should look for instructions that are specific to your macOS version.

**Comment by achew22** [comment]
@coltonmorris I assume that you're using rules_typescript. If not I would need to find out how you're using this tool. If you are, can you try using the new "[idiomatic](https://github.com/bazelbuild/rules_typescript#installation)" npm dependencies version rather than self managed? I think that is where they want things to end up, and it means that there are several orders of magnitude fewer files to watch and it might just work. Along with some other changes made recently, you might have more fun using iBazel now.

**Comment by achew22** [comment]
We now watch directories instead of files so this shouldn't be a problem any more unless you have a pathological codebase. Please reopen if you have more issues
