### ISSUE TITLE
ibazel run crash doesn't shut down ts_devserver

### ISSUE THREAD

**Issue by IgorMinar** [bazelbuild/bazel-watcher#197]
Repro steps:

- run `ibazel run //my/app:server` (where my/app:server is a ts_devserver target)
- edit my/app/BUILD.bazel and make a typo
- ibazel crashes due to #194 
- edit my/app/BUILD.bazel and fix the typo
- run `ibazel run //my/app:server`
- ibazel crashes because the previous server is still running:

```
ibazel run packages/animations/docs/examples/dsl:server
Querying for files to watch...
WARNING: Switched off --watchfs again... temporarily falling back to manually checking files for changes
Runing packages/animations/docs/examples/dsl:server
Launching with notifications
listening on :35729
Loading:
Loading: 0 packages loaded
INFO: Analysed target //packages/animations/docs/examples/dsl:server (0 packages loaded).
INFO: Found 1 target...
[0 / 4] [-----] BazelWorkspaceStatusAction stable-status.txt
...
INFO: Elapsed time: 0.496s, Critical Path: 0.07s
INFO: 0 processes.
INFO: Build completed successfully, 3 total actions
INFO: Build completed successfully, 3 total actions
Starting...Triggering live reload
requesting reload: reload
Serving livereload script from http://localhost:35729/livereload.js?snipver=1
Server listening on http://localhost:5432/
listen tcp :5432: bind: address already in use
connected
```

Please note `listen tcp :5432: bind: address already in use`.

The expected behavior is that if ibazel or the underlying bazel run crashes it also shuts down the server or any other child processes of ibazel.

**Comment by achew22** [comment]
@IgorMinar this is an interesting side effect of #194 and I would be interested in coming up with a generalized way of ensuring the subprocess is killed. The specific issue here is still closed in that #194 is fixed and therefore we should be good, so lets consider this bug to be something of the form:

"If iBazel crashes while a process is running it should terminate that subprocess."

**Comment by IgorMinar** [comment]
sgtm

**Comment by mrmeku** [comment]
@achew22 I was wondering a bit about this issue. So I see that for every execution ibazel performs, it creates a process group for the child process and its descendants as can be seen here: https://github.com/bazelbuild/bazel-watcher/blob/da33b5a7864216827da8b105afb24837f73d634a/ibazel/process_group/process_group_unix.go#L32

According the the interface for [SysProcAttr](https://golang.org/pkg/syscall/#SysProcAttr) we have access to the process group ID.

But in our implementation for kill, we kill the PID instead of the process group ID https://github.com/bazelbuild/bazel-watcher/blob/da33b5a7864216827da8b105afb24837f73d634a/ibazel/process_group/process_group_unix.go#L45

I think we should be killing the entire process group rather than just the direct child. (I think you might have followed this blog article: https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773 because it has the same implementation). I don't know if you can count of the PID being equal to the Process group ID. Either way, if you change it to `SysProcAttr. Pgid` you do have that guarantee.

---

That all being said, I think to fix this specific bug you'd either need a top level try catch (if such a concept exists in go) which calls Kill on all spawned processes. Since you're my go to go expert, does go have such a concept?

**Comment by mrmeku** [comment]
Here's bazel logic for killing a process group (they use the process group ID): https://github.com/bazelbuild/bazel/blob/0db53014ce88bda5f41a0081b78ab09b53c497ae/src/main/tools/process-tools.h#L38

**Comment by IgorMinar** [comment]
I don't believe that this is stale.

**Comment by achew22** [comment]
Agreed. Removing stale

**Comment by IgorMinar** [comment]
Not stale.

**Comment by IgorMinar** [comment]
Please don't close this.
