### ISSUE TITLE
ibazel occasionally stops running on changes

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/bazel-watcher#23]
I haven't got much of a repro. I have `ibazel run //some:target` or `ibazel build //some:target` going, and it works for a while and eventually stops. I have fallen back to my earlier general purpose watching tool, but would like to be able to advise colleagues to use ibazel as it matures.

Is this a familiar issue to anyone?

Seen with ibazel built from commit 15a1ebd2695f250cdc04b23c83d1794499476d95 on Linux:
```
$ lsb_release --description                                               
Description:    Debian GNU/Linux testing (buster)   
$ uname -r           
4.11.0-1-amd64
```

**Comment by achew22** [comment]
Is this happening on run and test and build commands all? What is your OS/text editor?

**Comment by achew22** [comment]
This looks like a fairly popular problem to have with inodes. Sounds like the answer is to watch the directory instead of watching the file. It is probably worth extracting this out into a watcher class that exposes an interface. Reading peoples docs on writing watchers for Windows it sounds like some of the POSIX-y tricks may be incompatible with whatever windows does for filesystem watching.

**Comment by achew22** [comment]
All of the ways that I know we lose track of files have been fixed now. Feel free to try again at head.

**Comment by kamalmarhubi** [comment]
Thanks for the update! I'll give it a shot. :-)
