### ISSUE TITLE
--define flag not passed on properly

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-watcher#242]
running e.g. `ibazel run --define=key=val :target`, on a rule that is making use of this configuration value, it does not seem to get forwarded correctly and the rule does not have access to `key`.

**Comment by Globegitter** [comment]
@achew22 wow that was quick - I opened this to make sure I would also not forget myself and eventually look into this, but that made it much easier thanks! And yes, I am happy with a local build for now.

**Comment by achew22** [comment]
If you run into any more issues with flags, that's the file and it should
be pretty straightforward to add new entries. I don't require any
additional tests or anything if you find them since I can easily validate
them manually so send them in using the github web code editor, no need for
anything fancy. Cheers!

**Comment by Globegitter** [comment]
Interesting, so running `ibazel build --define ...` now works but running `ibazel run --define ...` does not.

**Comment by achew22** [comment]
Huh, could I have you open another issue where we can talk through that?

**Comment by Globegitter** [comment]
I am going on holiday tomorrow but will dig into this again once I am back.
