### ISSUE TITLE
ibazel don't watch for changes in external repository

### ISSUE THREAD

**Issue by a-ignatov-parc** [bazelbuild/bazel-watcher#274]
We have two workspaces. One uses targets from another to build an application. If we use `local_repository`, `ibazel` works as expected when we make changes in the main workspace and don't track anything in the external workspace.

Here is a [small repo](https://github.com/a-ignatov-parc/bazel-demo/tree/ibazel-demo) with similar workspace configuration that we have.

If we check the dependency graph, we'll find source files from external repo, so I guess `ibazel` just don't watch for changes.

```
bazel query "kind('source file', deps(set(//app:ts_lib)))" | grep "@bazel_demo_external"
@bazel_demo_external//module:hello.ts
```

It's quite uncomfortable when you need to restart dev-server for any changes made in external deps during local development.

**Comment by achew22** [comment]
@a-ignatov-parc, That indeeds sounds uncomfortable. From the last time I looked at this, the big problem is that there is [no way](https://stackoverflow.com/questions/46229831/how-do-you-query-for-a-list-of-all-repositories-that-are-available-in-a-workspac) to get a list of all the repositories that exist, let alone get information about which ones are local vs remote.

Additionally we will need a mapping from, in your example, `@bazel_demo_external` to `path = "../external". Do you know how to get those pieces of data?

If you can find the data, the next step would be creating a testcase. You can create `//e2e/local_repository` by cloning `//e2e/simple` and creating some [sample data](https://github.com/bazelbuild/bazel-watcher/blob/master/e2e/simple/simple_test.go#L48) that is similar to your repo. I would recommend using `sh_binary`s instead of `ts_library`s since it will mean you don't have to thread a `package.json` and `rules_nodejs` into the test suite.

**Comment by a-ignatov-parc** [comment]
@achew22 thank you for the info! Can we use `bazel info` to get information about repositories?

As far as I know, list of all external repositories can be found in `$(bazel info output_base)/external` directory and local repositories are symlinks.

For example:
```
~/Sites/bazel-demo/main(ibazel-demo) » ll $(bazel info output_base)/external
total 88
-rw-r--r--   1 antonignatov  wheel    43B Jul 16 20:17 @bazel_demo_external.marker
-rw-r--r--   1 antonignatov  wheel    43B Jul 16 20:17 @bazel_tools.marker
-rw-r--r--   1 antonignatov  wheel    43B Jul 16 13:31 @build_bazel_rules_nodejs.marker
-rw-r--r--   1 antonignatov  wheel   2.0K Jul 16 13:31 @local_config_cc.marker
-rw-r--r--   1 antonignatov  wheel   584B Jul 16 13:31 @local_config_cc_toolchains.marker
-rw-r--r--   1 antonignatov  wheel   246B Jul 16 13:41 @local_config_sh.marker
-rw-r--r--   1 antonignatov  wheel   153B Jul 16 13:41 @local_config_xcode.marker
-rw-r--r--   1 antonignatov  wheel   177B Jul 16 13:01 @nodejs.marker
-rw-r--r--   1 antonignatov  wheel   689B Jul 16 13:01 @npm.marker
-rw-r--r--   1 antonignatov  wheel   307B Jul 16 13:01 @npm_bazel_typescript.marker
-rw-r--r--   1 antonignatov  wheel    43B Jul 16 13:18 @platforms.marker
lrwxr-xr-x   1 antonignatov  wheel    45B Jul 16 20:17 bazel_demo_external -> /Users/antonignatov/Sites/bazel-demo/external
lrwxr-xr-x   1 antonignatov  wheel   103B Jul 16 20:17 bazel_tools -> /var/tmp/_bazel_antonignatov/install/cfd28aee65ccfaf160d1b21b376cdce7/_embedded_binaries/embedded_tools
drwxr-xr-x   9 antonignatov  wheel   288B Jul 16 13:31 build_bazel_rules_nodejs
drwxr-xr-x  13 antonignatov  wheel   416B Jul 16 13:31 local_config_cc
drwxr-xr-x   6 antonignatov  wheel   192B Jul 16 13:31 local_config_cc_toolchains
drwxr-xr-x   4 antonignatov  wheel   128B Jul 16 13:41 local_config_sh
drwxr-xr-x   5 antonignatov  wheel   160B Jul 16 13:41 local_config_xcode
drwxr-xr-x   7 antonignatov  wheel   224B Jul 16 13:01 nodejs
drwxr-xr-x  29 antonignatov  wheel   928B Jul 16 13:01 npm
drwxr-xr-x  17 antonignatov  wheel   544B Jul 16 13:01 npm_bazel_typescript
lrwxr-xr-x   1 antonignatov  wheel    98B Jul 16 13:18 platforms -> /var/tmp/_bazel_antonignatov/install/ce6f4f2448eb9c8cbd7a3124ff3ed8a3/_embedded_binaries/platforms
```

In this case, it sounds reasonable to combine information from `bazel query` and `bazel info` to add watchers to files from the query that are in symlinked external repositories and symlinks are not resolved in `$(bazel info install_base)` directory.

**Comment by excavador** [comment]
+1

I need it

**Comment by achew22** [comment]
@a-ignatov-parc, good find! Seems like that's all the information we would need to do this.

* Do you know if that also works for Windows? We can validate the functionality by writing an e2e test since that'll run on all supported OSes. If it doesn't work we might still merge it just for Linux/Mac and leave a `TODO`.
* I know a lot of people use the [`--override_repository`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--override_repository) when they are doing testing, which temporarily replaces a remote repo with a local one. Can you also test that works?

Do you need any more information from me on this, or do you think you can attempt a PR? Hopefully things are pretty sane in the repo, but if you would like me to point to a few candidate places to get started in happy to help.

Good luck, and I'm here if you need help.

**Comment by excavador** [comment]
up

**Comment by achew22** [comment]
@excavador would you be interested in picking up the PR? It seems pretty close to me

**Comment by a-ignatov-parc** [comment]
Sorry for keeping silence on this issue. My team is still interested in fixing this issue. I'll make another attempt, and if there will be no progress in two weeks, I'll try to cooperate with someone to make it happen.

**Comment by achew22** [comment]
@a-ignatov-parc, have you had any luck with this?

**Comment by excavador** [comment]
I need it

**Comment by achew22** [comment]
@excavador perfect! We have a mostly working patch that needs a little bit of love to be brought up to speed.

https://github.com/bazelbuild/bazel-watcher/pull/277

Would you be willing to fork that PR and finish up the remaining todo items?

**Comment by lewish** [comment]
I'm currently taking a look at forking the above PR and finishing it off, we also are in need of it!
@achew22 are you on bazelbuild.slack ?

**Comment by lewish** [comment]
@achew22 Can we cut a release with this in please?

**Comment by lewish** [comment]
Actually, hold that thought, I think we may want to fix this first - https://github.com/bazelbuild/bazel-watcher/issues/383
