### ISSUE TITLE
Clarification on tag/release workflow

### ISSUE THREAD

**Issue by sudoforge** [bazelbuild/bazel-watcher#296]
Hey there,

I'm working with the author of an Arch Linux package that is currently building `v0.10.2` of `ibazel` / `bazel-watcher`; I noted that the tag `v0.10.3` was available (but that it doesn't build with `bazel build ...`) and that there are (as of this comment) 23 commits to `master` since the tag `v0.10.3`:

```
➜ git rev-list v0.10.3...origin/master
5603789ae9b1bb4c56b3dbd35b7dde7d3e3e2e72
ef4d770c4fa6681507e9ae9df7f47508eba9a070
c563142930498e1e1617e9fedd63ce03c79b5918
c48650e7a4c27d8049cc269bdc4e43ef638e2681
3ba2506e8bb505e9f796e0376f40a2105fb5ff7c
4ae1b6d98c6058eede257f6209fbb61566968a38
5c31c966766eedbe677151cb508627fdad5fe059
cc87648527cfbc7dd8fdb7484176ac62345dfed5
e22acf9be4c349eb49a72dc931afb7ccbd41801b
c089d96c95c2aa7a0acff02f5a7a458abefed8ec
2a68eb9e77e26f8659ab19f388aef0cd7ca96191
2909faa9c164c2f083bfc579faa824aedaa2dba4
3f172b50309237ebcb217fdfcb20bd3010d7cdb3
4259108b33a9318ba5d0b3edede162edf9f71fc8
992a96e7a4989b0a238924ae0128b830cd8696da
0fd03d468ba816520c914dca275a84f3f74c032e
5bde2f10722e22372cd92f00e968805c3b399dd8
18bdb44832ccc533e0ab3923ef80060eeb24582d
f9cf206fccee2b8f459d5fa83eb2381faf6ed42a
7d93aa5f27acf2ce5ec48aca70268a63e3c0e6e8
6770465f1c66e9ae290a67d4b75ad4f8d5d0e82e
69df6b52958f176641a51dfb31268fd4fced3b72
686130f50cea274f7453f6abc8c5249654047462
```

For the sake of determining what to do with the outdated package currently building `v0.10.2`, would it be possible to get some clarity around the current release process and expectations of stability for downstream users?

**Comment by achew22** [comment]
Hey @sudoforge, thanks for the interest!

Right now the issue with v0.10.3 is that the method I'm using for packaging the binaries doesn't support stamping. This means that I have to manually generate the release artifacts and do all that jazz. I've been trying to run down the issue with Jay Conrad (from rules_go) and have created a test case that demonstrates the issue. I now need to construct a demo that shows that the expectation of a `rules_x` project is that it should stamp when depended on through a `genrule`. Once I work this out I will be back to maing regular releases. v0.10.3 is the first version where I discovered this bug, which is why it doesn't have release artifacts.

The normal expectation is that anything tagged should be completely usable and I'm surprised that v0.10.3 is not, can you provide the error that it gives? Maybe I can fix it and release another minor version bump to clear things up. Would that work?

**Comment by Kernald** [comment]
The issue that we have to package v0.10.3 is that it doesn't build anymore with recent versions of Bazel. I can't run a build right now to give you the exact errors I encounter (and I assume all of those are fixed at head).

**Comment by sudoforge** [comment]
To isolate the issue, I left some informatino in #297.

**Comment by achew22** [comment]
In here, can you confirm that the new v0.10.3 tag is actually buildable?

**Comment by Kernald** [comment]
It is indeed. Thanks!

**Comment by achew22** [comment]
Would you be willing to send a PR indicating how to install bazel-watcher on arch in the readme?

**Comment by Kernald** [comment]
Ha well, I've been beaten to it :-) I guess this issue can be closed now.

**Comment by achew22** [comment]
Thanks for filling the issue away. Cheers!
