### ISSUE TITLE
Proposal:  use bazel's cquery in place of query for queryForSourceFiles checks

### ISSUE THREAD

**Issue by josephperrott** [bazelbuild/bazel-watcher#305]
Currently ibazel uses `bazel query` to determine if the build graph has changed.  However `bazel query` does not allow for configurations to be considered. 

If you set a `--define` flag for your `build`s, every time ibazel runs `bazel query`, the analysis cache is invalidated in determining the `query` results only to have the results invalidated again by the next `build`.

If `bazel cquery` is used instead, the `--define` flag is now considered/valid and the correct graph is created.  

`cquery` inherits all of its flags from `build` (as does `run` and `test`) which leads to all supported flags in ibazel being able to be forwarded to the "query" checks

---

Under the hood the commands that are called by ibazel in this instance look something like this:
```
Calls: bazel build //path/to/module:target
      ^ creates analysis cache using `--define` flag configuration

Change made to a file

Calls: bazel query //path/to/module:target
      ^ creates new analysis cache without `--define` flag, throwing out old cache
Calls: bazel build //path/to/module:target
      ^ creates new analysis cache using `--define` flag, throwing out old cache
```

with `cquery` it would instead be:
```
Calls: bazel build //path/to/module:target
      ^ creates analysis cache using `--define` flag configuration

Change made to a file

Calls: bazel cquery //path/to/module:target
      ^ uses analysis cache already created, updating as necessary
Calls: bazel build //path/to/module:target
      ^ uses analysis cache already created
```

**Comment by achew22** [comment]
@josephperrott, I think this would be a really really great feature to add. I've been doing some repo cleanup with the goal of engaging you on this issue. How could I help get you engaged?

All the code for controlling the query operation lives inside a small block inside the bazel lib.

https://github.com/bazelbuild/bazel-watcher/blob/7741ff3b41c6c99290f20505df18652e9ac99aa3/bazel/bazel.go#L216-L244

It doesn't look to me like it would be that hard to add a new method `cquery` and then change all the callers over. Is this a thing I could interest you in?

I'm about to do a release that will add colors (YAY!) and fix a lot of the output formatting issues (YAY!) but would love to do a `v0.11.1` as early as this afternoon if you're interested.

**Comment by IgorMinar** [comment]
Don't close this please.

**Comment by IgorMinar** [comment]
not stale

**Comment by devversion** [comment]
@achew22 Thanks for working on this. I think unfortunately it's not improving things as there is still a `bazel query` call for determining the build files. This causes the analysis cache to be still discarded.

The goal would be that the analysis cache is not discarded. We could achieve this by using `cquery` for determining the build files, or by using always `bazel query` and allowing define variables.

`cquery` does not support buildfiles, but maybe we could make that work with upstream changes in bazel? Ideally though, `bazel query` would just support `--define` for the sake of not discarding analysis cache, unless I miss something here. This makes me wonder why the analysis cache is even discard at all if standard `bazel query` is supposed to just run as part of the loading phase.

**Comment by achew22** [comment]
@devversion this sounds like a great issue to open upstream on the Bazel main repo. Unfortunately I don't have enough time to spin up on that particular issue, but I would be interested in seeing what they say. It could be something as simple as changing a Boolean value somewhere. That's something I would be happy to do.

**Comment by juliexxia** [comment]
Hey y'all, bazel engineer here. @devversion is right, `query` just runs the loading phase which is why it doesn't respect any build flags (like `--define`). That also means it shouldn't be invalidating the analysis cache because it doesn't run the analysis phase. 

Out of curiosity, you're  running two `query` commands one after another and you're seeing symptoms that looks like analysis cache invalidation? What are those symptoms? 

As for bazel changes, adding `--define` respect to `query` isn't an option. `cquery` was created to be a query that respects build flags. But adding `buildfiles()` support to `cquery` seems possible to me. If I remember correctly, there wasn't any major technical reason this didn't happen, we just figured we'd implement when a need arose:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java;l=480

Here's the implementation in `query`:
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/query/BlazeQueryEnvironment.java;l=410

Bazel team probably doesn't have the cycles to own this but If you wanted to investigate/make this change in the bazel repo I'd be happy to shepherd your PRs through.
