### ISSUE TITLE
No artifacts uploaded for 0.12.0 and 0.11.2

### ISSUE THREAD

**Issue by Kernald** [bazelbuild/bazel-watcher#350]
I wanted to upload the Homebrew packages (bazelbuild/homebrew-tap#86), but realised that there were no binaries uploaded for those two tags. Is this intended?

**Comment by achew22** [comment]
Huh, terribly sorry about that. That was not the goal at all. There must be something wrong with the release script. I'll investigate.

**Comment by achew22** [comment]
I just uploaded it, but the 2nd time I get a duplicate key error:

```
Failed to upload one of assets: one of the goroutines failed: failed to upload asset: /tmp/tmp.ued3lfE3IH/ibazel_darwin_amd64: failed to upload release asset: /tmp/tmp.ued3lfE3IH/ibazel_darwin_amd64: POST https://uploads.github.com/repos/achew22/bazel-watcher/releases/23940478/assets?name=ibazel_darwin_amd64: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

I wonder if there is a propagation delay on the upload? Is it up there for you?

**Comment by Kernald** [comment]
I don't see any artifacts for the 0.11.2 and 0.12.0. I also have no idea how the GitHub API works, sorry...

**Comment by achew22** [comment]
I figured it out. Turns out I wasn't forcing the upload to happen to the correct user. There are a bunch of nicely uploaded artifacts on my [personal fork of the repo](https://github.com/achew22/bazel-watcher/releases). I just uploaded [`v0.12.2`](https://github.com/bazelbuild/bazel-watcher/releases/tag/v0.12.2) which has artifacts attached. Sorry about that and thanks for filing an issue.

**Comment by Kernald** [comment]
Ha no worries, thanks for fixing it so quickly!
