### ISSUE TITLE
file watcher triggers too much

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#4]
If I carefully write to a file with a simple unix tool, like
`echo "" >> file` then I see exactly one rebuild when watching `file`.
But with any editor, after saving a file I see a bunch of rebuilds. On linux with VScode, I saw exactly two rebuilds, but on Mac it triggers endlessly and the `ibazel` command needs to be killed.

**Comment by mprobst** [comment]
iblaze specifically debounces the writes for that reason, it triggers on the first fs event, but then collects fs events for another 100 ms (or so, not sure about the number). The reason is that most editors don't just write a file, they have some dance like writing a new copy, then move the copy over the old file, and sometimes even moving the old file to a backup before that, which of course causes multiple events.

**Comment by achew22** [comment]
@alexeagle, is this happening on macOS? It could be additionally related to howeyc/fsnotify#62. The correct solution is to debounce this but while I look into how to do that it might be helpful to try their suggested fix of turning off spotlight indexing.
