### ISSUE TITLE
allow livereload to use a configurable hostname for the url

### ISSUE THREAD

**Issue by erickj** [bazelbuild/bazel-watcher#403]
https://github.com/bazelbuild/bazel-watcher/blob/e695e93213e803ca4091f39ef121fbddb2d39c42/ibazel/live_reload/server.go#L101

the URL construction hardcodes 'localhost', but if the iblaze instance is running on a workstation machine while I develop from a remote machine then livereload fails due to the wrong URL.

a way to configure the hostname for livereload would be useful here. maybe a flag? something like `iblaze -live_reload_host=mymachine run //my:devserver` might work.

**Comment by achew22** [comment]
@erickj sorry for the very slow response here. This is an interesting usecase.

As a temporary fix while we talk through this, you might consider using a url parser before rendering the live reload url in your code and replacing the hostname.

I'm very reluctant to add new flags to ibazel since it's trying to be the smallest shim between bazel and a tight development loop as possible. What would you think about exposing the port that the live reload server runs on in a different environment variable?

**Comment by erickj** [comment]
For a temp fix I've just been using an SSH port forward. The only pain point here is that it's only able to be setup after iblaze is started due to the random port selection.

This works for now, however I still think a configurable hostname is a very valid use case. I'm not sure that i understand the hesitation at allowing configuration of it. Alternatively instead of hardcoding 'localhost' you may consider using the hostname of the machine - although that's probably a bigger rats nest.

In any case my direct issue has a work around

**Comment by achew22** [comment]
> For a temp fix I've just been using an SSH port forward. The only pain point here is that it's only able to be setup after iblaze is started due to the random port selection.

Oof, that's annoying. Sorry about that.

> This works for now, however I still think a configurable hostname is a very valid use case.

I'm sorry if it came off as me saying it isn't a valid use case. Of course it is a valid use case!

The hesitation is that right now ibazel doesn't really have any flags that control its behavior, everything is either inferred, has a sane default, or is a thing where there are security implications for turning it on so giving the option is a must. For the most part people can just run `ibazel` and it works like `bazel` but has more features. I want to keep the number of control knobs to approximately 0 so that anyone can jump in and enjoy ibazel in its fullest form without having to read a dozen manpages.

The point of asking this question is to start a conversation and see if there is another way we can solve this that doesn't result in more fiddly control knobs and gives you what you need. Do you have any ideas on that front?

**Comment by erickj** [comment]
> without having to read a dozen manpages.
> Do you have any ideas on that front?

Not particularly, however i come from the mindset that the first 2 commands I issue with a new binary/script are generally `man newthing` and `newthing -h`.

Given the second server mechanism of the live reload script you'll always need to write a hostname into the script URL of the script tag because it's not the base url. The only other crazy workaround here would be to reverse proxy to the ts devserver through the ibazel server, but that would be a ton of work and potentially require fragile url rewriting.

If a simpler fix exists than a flag (or some other config mechanism), then i don't immediately see it
