### ISSUE TITLE
The test command should not build unrelated non-test targets

### ISSUE THREAD

**Issue by mthurlin** [bazelbuild/bazel-watcher#415]
**Describe the bug**
When running `ibazel test //...` and changing a source file, I do not expect non-test targets to be rebuilt unless they are required for tests.

1. `git clone https://github.com/mthurlin/bazel-typescript-app`
2. `ibazel test //...`
3. Modify `demo/myframework/doublestring.ts` (for example, replace second `s` with `hello`: `return add(s, "hello");`)
4. Save file and notice that the test itself will fail quickly (as expected), but it then rebuilds the Webpack prod bundle `//demo/bundle:prod-bundle` and it takes unnecessary time before the test results are presented. The prod bundle is not required for any of the tests.

**Expected behavior**
I expected it to rebuild all test targets depending on the changed file, but not unrelated non-test targets depending on that file.

Workaround: The following behaves as expected, but I guess this will run into command-line limits when the number of tests is big:
```
ibazel test `bazel query 'tests(//...)'`
```

**Version (please complete the following information):**
 - OS: OSX 10.15.6
 - ibazel Version 0.13.1
 - Bazel version
```Build label: 3.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:55:48 2020 (1586177748)
Build timestamp: 1586177748
Build timestamp as int: 1586177748```

**Comment by achew22** [comment]
> When running ibazel test //... and changing a source file, I do not expect non-test targets to be rebuilt unless they are required for tests.

Unfortunately `ibazel` invokes the equivalent `bazel` command every time a file that is in the transitive closure of the files in the input query. Simply said, look at all the transitive dependencies (I would use [`bazel query`](https://docs.bazel.build/versions/master/query.html)'s `somepath` operator) and see if there is a dependency you hadn't considered. `bazel` caches heavily and will only retest targets that could have, conceivably, been altered by the modified files. It would be nice if there was a better way to do this, but unfortunately I think one of a few things is possible here:

1. There actually is a dependency on the webpack bundle in one of your tests in which case, the webpack bundle is changed so that test must be run in order to guarantee
1. Something about your invocation of `bazel test` (through `ibazel test`) has tagged the webpack bundle as a test target that must be executed
1. Your caching is not configured correctly and is not tracking the previously completed test
1. There is a bug in either Bazel's cache validity tracking
1. Something else that I can't think of off the top of my head (gotta have a catch all 😉 )

I would recommend investigating these options, but ultimately I think you will leave unsatisfied. I would especially investigate 1 and 2. Your best hope here is probably to be a bit more specific than `//...`when running `ibazel` and instead just get the directory, subdirectory, or target that is implicated in the tests you actually want to run.

Best of luck. If you have any more questions feel free to post back here.
