### ISSUE TITLE
Killing old process only when the build succeeds.

### ISSUE THREAD

**Issue by gyakushev** [bazelbuild/bazel-watcher#437]
I use ibazel to restart web server that takes some time to compile.
Is it possible to configure ibazel so it only kills the currently running binary after the build succeeds to avoid downtime?
If not, can you point me to a code location where it can be adjusted?

Thanks!

**Comment by achew22** [comment]
Hey @gyakushev,

This is definitely something that could be changed but it will require a little bit of effort. Right now it just invokes `bazel run` to actually run a program directly. It's a pretty simple process. ibazel is just a state machine that emits events to listeners. One of them is the command listener. It has a [`NotifyOfChange`](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/command/default_command.go#L88) method, which terminates the old process and then starts the new one.

In order to get this to work in the way you describe, you would have to modify it to `bazel build` the target (while the subprocess is still running) then upon success, get the name of the freshly compiled binary and actually invoke it. Some of this logic already exists in [`notify_command.go`](https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/command/notify_command.go), so you could probably extract some common logic there and use it.

Is this a thing you'd be interested in contributing?

**Comment by gyakushev** [comment]
If we do it for ourselves we'll be sure to send you the PR.

**Comment by achew22** [comment]
@gyakushev did you have any luck with this?

**Comment by gyakushev** [comment]
@achew22 sorry, switched to other stuff. Highly unlikely we'll work on it any time soon.
