### ISSUE TITLE
avoid version problems for node users

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#45]
There are two ways:

1) recommend `PATH=./node_modules/.bin:$PATH` so that if you are in a project directory where ibazel@x.y.z is installed, you get that version. @vsavkin suggests this. But if you're in a child directory (common for bazel users since it does a good job in this case) it doesn't work

2) when ibazel runs, it checks if there is a locally installed copy, and exec()s that one instead. gulp and angular-cli do it this way. @hansl suggests this

**Comment by ittaiz** [comment]
What is the current state?

**Comment by alexeagle** [comment]
Currently you either do a global install, then get the global version anywhere you run the tool, or list ibazel in your package.json#devDependencies, then you have to run it like `./node_modules/.bin/ibazel`

**Comment by ittaiz** [comment]
got it. thanks

**Comment by mrmeku** [comment]
I think this issue is a bit tricky since you can specify multiple targets for bazel to build/run

bazel build :some_target path:some_other_target

Should we only try to pick the local ibazel if they specify one target? Or maybe only if they are in a subdirectory with a local bazel installation (so running ibazel from outside the project directory would do use the global installed version)?

I think we need to think about a really easy to understand heuristic we can use so that we can communicate that to ibazel users

**Comment by alexeagle** [comment]
I don't think it matters what the target patterns are.
You just look in the cwd() where the ibazel is run. If you find a locally installed in `./node_modules` or `../(../)+node_modules` then you use that (following node module resolution semantics). Finally you give up and run the globally installed one.

**Comment by mrmeku** [comment]
So basically we punt on if they have a local installation but invoke ibazel
from a parent directory of their project. I think that's pretty reasonable.

**Comment by achew22** [comment]
Is there a good way to scan for `node_modules` directories other than to recurse up and see if it exists?

**Comment by alexeagle** [comment]
That's what other implementations do, I believe
