### ISSUE TITLE
"ibazel run" and "bazel run" of a nodejs_binary rule execute in different working directories

### ISSUE THREAD

**Issue by jakelauer** [bazelbuild/bazel-watcher#497]
**Describe the bug**
"ibazel run" and "bazel run" of a nodejs_binary rule execute in different working directories. When running via bazel, the rule executes in the bazel ~~sandbox~~ execution directory, but with ibazel, it runs in the workspace directory.

**Reproduction instructions**
**logdir.js**
```
console.log(__dirname);
```

**BUILD**
```
nodejs_binary(
	name = "logdir",
	entry_point = "logdir.js",
	data = [
		"logdir.js"
	]
)
```

1. In a bazel project using nodejs_rules, create the two files above
2. Run `ibazel run //src/path/to/folder:logdir` and observe output
3. Run `bazel run //src/path/to/folder:logdir` and observe output

**Expected behavior**
Logged directory in both cases is the ~~sandbox~~ execution directory (e.g. `C:\users\user\_bazel~1\6n4rhrox\execroot\repo~1\bazel-~1\x64_wi~1\bin\src\path\to\folder\logdirba~2.run\net_bu~1\src\path\to\folder`

**Actual Behavior**
bazel's logged directory is in the ~~sandbox~~ execution directory as expected, but ibazel's logged directory is in the source tree

**Version (please complete the following information):**
 - OS: Win 10
 - ibazel Version: 0.15.10
 - Bazel version:
```
Bazelisk version: v1.10.0
Build label: 4.1.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri May 21 11:17:01 2021 (1621595821)
Build timestamp: 1621595821
Build timestamp as int: 1621595821
```

**Comment by pauldraper** [comment]
Nit: It's not running in a sandbox directory, but rather the executable's execution directory, which is `<executable>/<workspace>`.

It should be relatively straightforward for ibazel to execute the process in this directory as well.

**Comment by jakelauer** [comment]
Ah yeah, thanks for the correction there.

**Comment by achew22** [comment]
`ibazel run` only runs `bazel run` on behalf of the user, it doesn't do anything special with working directories or anything like that. I am reluctant to implement something like this, because it means that people using `ibazel run` would have a different experience from people running `bazel run` which will lead to all kinds of confusion in other ways.

If you'd like this behavior, it would be best to contribute it back to the `rules_nodejs` project, or modify the `main` of your program to read the environment variables and behave accordingly.

If you think I'm totally off base here, please reopen the bug and let's talk about it.

**Comment by jakelauer** [comment]
I'm not requesting this behavior, I'm saying this _is_ the behavior I'm seeing, and I don't want it. I want `bazel run` and `ibazel run` to be identical, but they are not.

**Comment by jakelauer** [comment]
I'd reopen, but I'm not sure how to, haha.
