### ISSUE TITLE
ibazel writes IBAZEL_BUILD_COMPLETED FAILURE to stdin even for successful builds

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-watcher#56]
In my prototype devserver that uses ibazel from HEAD, I had to listen for FAILURE
https://github.com/alexeagle/angular-bazel-example/blob/98af46d27bab378e4ed5f14799c80578f0287d55/airplane/devserver.js#L9
because ibazel never reports SUCCESS

**Comment by mrmeku** [comment]
I'm going to document a bit of research I've done on this bug. It appears that the "error" that ibazel identifies is one is causes it self. To see if an error is produced ibazel calls the .Wait method on the Cmd object it uses to represent an invocation of bazel. However, when it calls Wait to see if there was an error the error produced reads "Wait was already called". So I think the key to fixing this bug is to ensure that wait is only called once. If we do that then bazel should go down the code path which logs IBAZEL_BUILD_COMPLETED SUCCESS
