### ISSUE TITLE
PKGBUILD for Arch Linux

### ISSUE THREAD

**Issue by justbuchanan** [bazelbuild/bazel-watcher#66]
Just FYI, I added an unofficial package for Arch Linux at: https://aur.archlinux.org/packages/ibazel-git/.

If you have any suggestions or issues with it, please let me know.

Note: It currently doesn't build without the changes from https://github.com/bazelbuild/bazel-watcher/pull/61.

**Comment by achew22** [comment]
Will do. Thanks! I don't know much about Arch's package manager but it looks like installing this will install its dependency (Bazel) and that sounds perfect to me! I'm going to close this since I don't think there is any action for me here. If there is anything I can do to help please free to file an issue here. I just merged #61 so it should work now. YAY!
